---
name: Build
on:
  push:
    branches:
      - master
jobs:
  release-docker-build:
    name: Release Docker Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        id: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - name: Build PNGs
        id: png
        run: |
          echo ${PWD}/svg/
          find ${PWD}/svg/ -type f -name \*.svg | while read LINE
          do
            INPUTDIR=$( dirname ${LINE})
            OUTPUTDIR=${INPUTDIR/#${PWD}\/svg/${PWD}\/png}
            INPUT=$( basename ${LINE})
            OUTPUT=${INPUT/.svg/.png}
            echo docker run --rm -v ${INPUTDIR}:/input -v ${OUTPUTDIR}:/output docker.io/illallangi/toolbx:v0.6.0 rsvg-convert /input/${INPUT} -o /output/${OUTPUT} -d 600 -p 600
            docker run --rm -v ${INPUTDIR}:/input -v ${OUTPUTDIR}:/output docker.io/illallangi/toolbx:v0.6.0 rsvg-convert /input/${INPUT} -o /output/${OUTPUT} -d 600 -p 600
            echo
          done
      - name: Archive PNG files for Release
        uses: thedoctor0/zip-release@master
        with:
          filename: png.zip
          directory: png
      - name: Archive SVG files for Release
        uses: thedoctor0/zip-release@master
        with:
          filename: svg.zip
          directory: svg
      - name: Find
        run: |
          find ${PWD}
